// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionResponse {
    #[prost(message, optional, tag = "1")]
    pub history: ::core::option::Option<HistoryWrapper>,
    #[prost(bytes = "vec", tag = "5")]
    pub flags_f5: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "6")]
    pub auth: ::core::option::Option<AuthInfo>,
    #[prost(bytes = "vec", tag = "7")]
    pub f7: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "9")]
    pub f9: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "11")]
    pub f11: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "15")]
    pub user_id_raw: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "18")]
    pub f18: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "19")]
    pub context: ::core::option::Option<UserContext>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HistoryWrapper {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<HistoryEntry>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HistoryEntry {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    /// Nested details are stored raw to preserve structure
    #[prost(bytes = "vec", tag = "2")]
    pub detail_raw: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthInfo {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub id_token: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub meta: ::core::option::Option<AuthMetadata>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthMetadata {
    #[prost(int64, tag = "1")]
    pub expiry_timestamp: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserContext {
    #[prost(int32, tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub plan_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "33")]
    pub models: ::core::option::Option<ModelConfig>,
    #[prost(message, optional, tag = "36")]
    pub plan: ::core::option::Option<PlanConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelConfig {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<ModelItem>,
    #[prost(message, optional, tag = "2")]
    pub recommended: ::core::option::Option<RecommendedModel>,
    #[prost(bytes = "vec", tag = "3")]
    pub unknown_f3: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelItem {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub unknown_f2: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "5")]
    pub unknown_f5: i64,
    #[prost(int64, tag = "11")]
    pub unknown_f11: i64,
    #[prost(bytes = "vec", tag = "15")]
    pub unknown_f15: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecommendedModel {
    #[prost(string, repeated, tag = "1")]
    pub names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bytes = "vec", tag = "2")]
    pub unknown_f2: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlanConfig {
    #[prost(string, tag = "1")]
    pub slug: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub upgrade_url: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub upgrade_msg: ::prost::alloc::string::String,
}
